package com.example.travel_roulette.vo

data class PrefectureSeed(
    val isHokkaido: Boolean = true,
    val isAomori: Boolean = true,
    val isAkita: Boolean = true,
    val isIwate: Boolean = true,
    val isYamagata: Boolean = true,
    val isMiyagi: Boolean = true,
    val isHukushima: Boolean = true,
    val isGunma: Boolean = true,
    val isTochigi: Boolean = true,
    val isSaitama: Boolean = true,
    val isIbaraki: Boolean = true,
    val isTokyo: Boolean = true,
    val isChiba: Boolean = true,
    val isKanagawa: Boolean = true,
    val isNigata: Boolean = true,
    val isNagano: Boolean = true,
    val isYamanashi: Boolean = true,
    val isShizuoka: Boolean = true,
    val isToyama: Boolean = true,
    val isGihu: Boolean = true,
    val isAichi: Boolean = true,
    val isIshikawa: Boolean = true,
    val isHukui: Boolean = true,
    val isShiga: Boolean = true,
    val isMie: Boolean = true,
    val isKyoto: Boolean = true,
    val isNara: Boolean = true,
    val isHyogo: Boolean = true,
    val isOsaka: Boolean = true,
    val isWakayama: Boolean = true,
    val isTottori: Boolean = true,
    val isOkayama: Boolean = true,
    val isShimane: Boolean = true,
    val isHiroshima: Boolean = true,
    val isYamaguchi: Boolean = true,
    val isKagawa: Boolean = true,
    val isTokushima: Boolean = true,
    val isEhime: Boolean = true,
    val isKochi: Boolean = true,
    val isHukuoka: Boolean = true,
    val isNagasaki: Boolean = true,
    val isSaga: Boolean = true,
    val isOita: Boolean = true,
    val isMiyazaki: Boolean = true,
    val isKumamoto: Boolean = true,
    val isKagoshima: Boolean = true,
    val isOkinawa: Boolean = true,
)

enum class Area {
    Tohoku,
    Kanto,
    Chubu,
    Kansai,
    Chugoku,
    Shikoku,
    Kyushu
}